=== smartgridadsc/CyberRange/ScadaBR/Scada.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- XML file: add line 

<ScadaBR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="ScadaBR.xsd">  

-->
	<xs:element name="Scada">
        <xs:complexType>
			<xs:sequence>
            	<xs:element name="dataSources" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="xid" type ="xs:string"/> 
                			<xs:element name="type" type ="xs:string"/>
							<xs:element name="updatePeriodType" type ="DSupdatePeriodType"/>
							<xs:element name="transportType" type ="DStransportType"/>					
							<xs:element name="host" type ="xs:string"/>
							<xs:element name="name" type ="xs:string"/>
                			<xs:element name="port" type ="DSport"/>
							<xs:element name="updatePeriods" type ="DSupdatePeriods"/>               			
                        </xs:all>
                    </xs:complexType>
                    <!-- 
                    <xs:key name="DSxidKey">
        				<xs:selector xpath="xid" />
        				<xs:field xpath="@DSxid"/>     				
    				</xs:key>
                    <xs:key name="DStypeKey">
        				<xs:selector xpath="type" />
        				<xs:field xpath="@DStype"/>        				
    				</xs:key> 
                    <xs:key name="DSupdatePeriodTypeKey">
        				<xs:selector xpath="updatePeriodType" />
        				<xs:field xpath="@DSupdatePeriodType"/>        				
    				</xs:key>
    				<xs:key name="DStransportTypeKey">
        				<xs:selector xpath="transportType" />
        				<xs:field xpath="@DStransportType"/>        				
    				</xs:key>       				  
                    <xs:key name="DShostKey">
        				<xs:selector xpath="host" />
        				<xs:field xpath="@DShost"/>        				
    				</xs:key>     
    				<xs:key name="DSnameKey">
        				<xs:selector xpath="name" />
        				<xs:field xpath="@DSname"/>        				
    				</xs:key> 
    				<xs:key name="DSportKey">
        				<xs:selector xpath="port" />
        				<xs:field xpath="@DSport"/>	        				
    				</xs:key>
    				<xs:key name="DSupdatePeriodsKey">
        				<xs:selector xpath="updatePeriods" />
        				<xs:field xpath="@DSupdatePeriods"/>        				
    				</xs:key>   	-->			 				
          	 	 </xs:element>
            
           		 <xs:element name="dataPoints" maxOccurs="unbounded">
           		    <xs:complexType>  
           		    	<xs:all>             		    	 
            		        <xs:element name="xid" type ="xs:string"/>
            		        <xs:element name="pointLocator">
                    			<xs:complexType>
                        			<xs:all>
                        				<xs:element name="range" type="DPRange"/>
                        				<xs:element name="modbusDataType" type="DPmodbusDataType"/>
                            			<xs:element name="offset" type="xs:integer"/>
                        			</xs:all>
                    			</xs:complexType>
                			</xs:element>
                			<xs:element name="engineeringUnits" type ="DPengineeringUnits"/>
							<xs:element name="dataSourceXid" type ="xs:string"/>
							<xs:element name="deviceName" type ="xs:string"/>					
							<xs:element name="name" type ="xs:string"/>
						</xs:all>
           			</xs:complexType>
         		</xs:element>
			</xs:sequence>
        </xs:complexType>      
	</xs:element>
	
	
	
	<xs:simpleType name="DSupdatePeriodType">	
    	<xs:restriction base="xs:string">  
    	  	<xs:enumeration value="MILLISECONDS"/>
    		<xs:enumeration value="SECONDS"/>
			<xs:enumeration value="MINUTES"/>
			<xs:enumeration value="HOURS"/>
		</xs:restriction>
		
	</xs:simpleType>
	
		<xs:simpleType name="DStransportType">	
    	<xs:restriction base="xs:string">  
    	  	<xs:enumeration value="TCP"/>
    		<xs:enumeration value="TCP_KEEP_ALIVE"/>
			<xs:enumeration value="UDP"/>
		</xs:restriction>
	</xs:simpleType>
		
	<xs:simpleType name="DSport">	
    	<xs:restriction base="xs:integer">  
      		<xs:minInclusive value="0"/>
      		<xs:maxInclusive value="65353"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="DSupdatePeriods">	
    	<xs:restriction base="xs:integer">  
      		<xs:minInclusive value="0"/>
      		<xs:maxInclusive value="9999"/>
		</xs:restriction>
	</xs:simpleType>	
		
	<xs:simpleType name="DPRange">	
    	<xs:restriction base="xs:string">  
    	  	<xs:enumeration value="COIL_STATUS"/>
    		<xs:enumeration value="INPUT_STATUS"/>
			<xs:enumeration value="HOLDING_REGISTER"/>
			<xs:enumeration value="INPUT_REGISTER"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="DPmodbusDataType">	
    	<xs:restriction base="xs:string">  
    	  	<xs:enumeration value="BINARY"/>
    		<xs:enumeration value="TWO_BYTE_UNSIGNED_INTEGER"/>
    		<xs:enumeration value="TWO_BYTE_BCD"/>
    		<xs:enumeration value="FOUR_BYTE_UNSIGNED_INTEGER"/>
    		<xs:enumeration value="FOUR_BYTE_SIGNED_INTEGER"/>
    		<xs:enumeration value="FOUR_BYTE_UNSIGNED_INTEGER_SWAPPED"/>
    		<xs:enumeration value="FOUR_BYTE_SIGNED_INTEGER_SWAPPED"/>
    		<xs:enumeration value="FOUR_BYTE_FLOAT"/>
    		<xs:enumeration value="FOUR_BYTE_FLOAT_SWAPPED"/>
    		<xs:enumeration value="FOUR_BYTE_FLOAT_SWAPPED_INVERTED"/>
    		<xs:enumeration value="FOUR_BYTE_BCD"/>
    		<xs:enumeration value="EIGHT_BYTE_UNSIGNED_INTEGER"/>
    		<xs:enumeration value="EIGHT_BYTE_SIGNED_INTEGER"/>
    		<xs:enumeration value="EIGHT_BYTE_UNSIGNED_INTEGER_SWAPPED"/>
    		<xs:enumeration value="EIGHT_BYTE_SIGNED_INTEGER_SWAPPED"/>
    		<xs:enumeration value="EIGHT_BYTE_FLOAT"/>
    		<xs:enumeration value="EIGHT_BYTE_FLOAT_SWAPPED"/>
    		<xs:enumeration value="FIXED_LENGTH_STRING"/>
    		<xs:enumeration value="VARIABLE_LENGTH_STRING"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="DPengineeringUnits">	
    	<xs:restriction base="xs:string">  
    	  	<xs:enumeration value=""/>
    		<xs:enumeration value="VOLTS"/>
    		<xs:enumeration value="AMPERES"/>
    		<xs:enumeration value="HERTZ"/>
    		<xs:enumeration value="KILOWATTS"/>
    		<xs:enumeration value="DEGREES_CELSIUS"/>
    		<xs:enumeration value="PERCENT"/>
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== smartgridadsc/CyberRange/Demo V1/SCADA/test.xml
<?xml version="1.0"?>
<Scada xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Scada.xsd">
 <dataSources>
	<xid>DS_051944</xid>
	<type>MODBUS_IP</type>
	<updatePeriodType>MILLISECONDS</updatePeriodType>
	<transportType>TCP</transportType>
	<host>192.168.10.11</host>
	<name>plc1</name>
	<port>502</port>
	<updatePeriods>500</updatePeriods>
</dataSources>
<dataSources>
	<xid>DS_063057</xid>
	<type>MODBUS_IP</type>
	<updatePeriodType>MILLISECONDS</updatePeriodType>
	<transportType>TCP</transportType>
	<host>192.168.10.12</host>
	<name>plc2</name>
	<port>502</port>
	<updatePeriods>500</updatePeriods>
</dataSources>

<dataPoints>
	<xid>DP_862782</xid>
	<pointLocator>
		<range>HOLDING_REGISTER</range>
		<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>
		<offset>2848</offset>
	</pointLocator>
	<engineeringUnits/>
	<dataSourceXid>DS_051944</dataSourceXid>
	<deviceName>plc1</deviceName>
	<name>line_load_percent00</name>
</dataPoints>

<dataPoints>
	<xid>DP_798499</xid>
	<pointLocator>
		<range>HOLDING_REGISTER</range>
		<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>
		<offset>2850</offset>
	</pointLocator>
	<engineeringUnits/>
	<dataSourceXid>DS_051944</dataSourceXid>
	<deviceName>plc1</deviceName>
	<name>line_load_percent01</name>
</dataPoints>

<dataPoints>
<xid>DP_158827</xid>
	<pointLocator>
		<range>HOLDING_REGISTER</range>
		<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>
		<offset>2852</offset>
	</pointLocator>
<engineeringUnits/>
<dataSourceXid>DS_051944</dataSourceXid>
<deviceName>plc1</deviceName>
<name>line_load_percent02</name>
</dataPoints>


<dataPoints>
	<xid>DP_252518</xid>
	<pointLocator>
		<range>HOLDING_REGISTER</range>
		<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>
		<offset>2854</offset>
	</pointLocator>
	<engineeringUnits/>
	<dataSourceXid>DS_051944</dataSourceXid>
	<deviceName>plc1</deviceName>
	<name>line_load_percent03</name>
</dataPoints>

<dataPoints>
	<xid>DP_028804</xid>
	<pointLocator>
		<range>HOLDING_REGISTER</range>
		<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>
		<offset>2856</offset>
	</pointLocator>
	<engineeringUnits/>
	<dataSourceXid>DS_051944</dataSourceXid>
	<deviceName>plc1</deviceName>
	<name>line_load_percent04</name>
</dataPoints>

<dataPoints>
	<xid>DP_558661</xid>
	<pointLocator>
		<range>HOLDING_REGISTER</range>
		<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>
		<offset>2858</offset>
	</pointLocator>
	<engineeringUnits/>
	<dataSourceXid>DS_051944</dataSourceXid>
	<deviceName>plc1</deviceName>
	<name>line_load_percent05</name>
</dataPoints>

<dataPoints>
	<xid>DP_939138</xid>
	<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2860</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_load_percent06</name>














</dataPoints>


<dataPoints>
	<xid>DP_182735</xid>
	<pointLocator>
		<range>HOLDING_REGISTER</range>
		<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>
		<offset>2862</offset>
	</pointLocator>
	<engineeringUnits/>
	<dataSourceXid>DS_051944</dataSourceXid>
	<deviceName>plc1</deviceName>
	<name>line_load_percent10</name>
</dataPoints>

<dataPoints>
	<xid>DP_035618</xid>
	<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2864</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_load_percent11</name>














</dataPoints>


<dataPoints>

<xid>DP_374709</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2048</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_00</name>














</dataPoints>


<dataPoints>

<xid>DP_971230</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2050</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_01</name>














</dataPoints>


<dataPoints>

<xid>DP_134181</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2052</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_02</name>














</dataPoints>


<dataPoints>

<xid>DP_816861</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2054</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_03</name>














</dataPoints>


<dataPoints>

<xid>DP_730257</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2056</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_04</name>














</dataPoints>


<dataPoints>

<xid>DP_759510</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2058</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_05</name>














</dataPoints>


<dataPoints>

<xid>DP_819606</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2060</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_06</name>














</dataPoints>


<dataPoints>

<xid>DP_762456</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2062</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_10</name>














</dataPoints>


<dataPoints>

<xid>DP_667057</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2064</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_11</name>














</dataPoints>


<dataPoints>

<xid>DP_458860</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2066</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_12</name>














</dataPoints>


<dataPoints>

<xid>DP_455711</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2068</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_13</name>














</dataPoints>


<dataPoints>

<xid>DP_543540</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2070</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_14</name>














</dataPoints>


<dataPoints>

<xid>DP_201835</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2072</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_15</name>














</dataPoints>


<dataPoints>

<xid>DP_440203</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2074</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_16</name>














</dataPoints>


<dataPoints>

<xid>DP_309268</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2076</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>line_real_17</name>














</dataPoints>


<dataPoints>

<xid>DP_794263</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2248</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>load_real_00</name>














</dataPoints>


<dataPoints>

<xid>DP_125185</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>

<modbusDataType>FOUR_BYTE_FLOAT</modbusDataType>









<offset>2250</offset>









</pointLocator>



<engineeringUnits/>





<dataSourceXid>DS_051944</dataSourceXid>



<deviceName>plc1</deviceName>











<name>load_real_01</name>














</dataPoints>


<dataPoints>

<xid>DP_431621</xid>










<pointLocator>

<range>HOLDING_REGISTER</range>
